name: Pester
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  pester:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - shell: pwsh
        run: Invoke-Pester -Path tests -CI
